### PR TITLE
Update snow.i3d

### PR DESCRIPTION
**Pull request by ItZzShady**
Changed 'dropMinVelocity' and 'dropMaxVelocity'. 
Removed Mist effect.

### CODE REVIEW

**Comment by joskuijpers** [comment]
Hi @ItZzShady 

Thank you. Could you explain why the changes are required? Why is it bad to have this mist?

I don't think we use this rain type yet. How have you tried it out?

**Comment by ItZzShady** [comment]
Hi @joskuijpers 

It looks nicer without the mist and the slower snow particles! I replaced my rain particles with the snow particles (and my new texture. But that is not yet finished).

**Comment by joskuijpers** [comment]
Awesome, can you make a screenshot for me?

**Comment by ItZzShady** [comment]
My snow texture looks very ugly.. I know :)

And please dont Pull my request, there is a small mistake from my part. I think ingame is a wind effect. Sometimes it will look nice and sometimes it looks very fast :/
Sorry for that!

**Comment by joskuijpers** [comment]
Oh it seems we have received a snow particle system from Gary (FSModding) last week. Will upload it so you can look at it.

**Comment by joskuijpers** [comment]
If you have suggestions for the new snow, please open an issue :)

**Pull request closed without merging**
