### PR TITLE
Update modDesc_l10n_pl.xml

### PR DESCRIPTION
**Pull request by Dzi4d3k**
I made translation that is not direct, but which I feel will fit properly and look more natural.

### CODE REVIEW

**Comment by theSeb1979** [comment]
Hey dziadek. In "Gleba jest zamarznięta. Nie można jej uprawiać!" shouldn't gleba not be ziemia?

**Comment by Dzi4d3k** [comment]
Well, we could use both, but "gleba" is more formal translation of a "soil" and are more related to farming. Now "ziemia" is used for naming the ground. "Ziemia" can be also taken into hand or on the shovel.
Also Earth (our planet) is named "Ziemia" in Polish. In this situation both would be just fine, but I felt that "gleba" would fit better.

**Comment by theSeb1979** [comment]
I left Poland when I was very young so will go with your suggestion. I just wasn't sure about gleba, but it's been a long time since I've used Polish :)

**Comment by Dzi4d3k** [comment]
Now I have question. I removed "TODO" texts in intros translation, however now in French translation I see them left. Do they mean that translation is TODO or intros are to TODO?

**Comment by theSeb1979** [comment]
I think it means that jos was still thinking about changing the english original text. You can leave them out to be honest. I guess I'll remove them from the French version too.

**Pull request merged**
