### PR TITLE
Update translation_fr.xml

### PR DESCRIPTION
**Pull request by Anonymous-any**
Patch correction#2

### CODE REVIEW

**Comment by joskuijpers** [comment]
Bon

**Comment by Anonymous-any** [comment]
Found this bug too :/

Error: C:/Users/pathuser/Downloads/My Games/FarmingSimulator2017/mods/FS17_seasons_master/src/loader.lua:124: unexpected symbol near 'if'

**Comment by joskuijpers** [comment]
Intentional, not a bug. Is to prevent the stealing by modsites.

**Comment by Anonymous-any** [comment]
It's ok:) but the download is not functional then and I must juggle with modded files cause I don't know what I must put for solve some code error.
Finally downloading on Github source Is not usable.

**Pull request merged**
